# Generated by Django 4.1.7 on 2023-02-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='cat_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
